- name: install repo
  ansible.builtin.yum_repository:
    name: epel
    description: docker repo
    file: external_repos
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: install packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io