- name: create group for docker
  ansible.builtin.group:
    name: docker
    state: present

- name: add ansible user to docker group
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: true

- name: conf logs
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: restart docker