#SPDX-License-Identifier: MIT-0
---
# tasks file for gitlab-runner

- ansible.builtin.include_tasks: runner_container.yml
- ansible.builtin.include_tasks: runner_shell.yml
- ansible.builtin.include_tasks: runner_register.yml
- ansible.builtin.include_tasks: runner_conf.yml