- when: executor == "shell"
  block:
    - when: ansible_os_family == "Debian"
      block:
        - name: keyrings dir
          ansible.builtin.file:
            path: /etc/apt/keyrings
            state: directory
            mode: "0755"

        - name: Download gitlab runner gpg key
          ansible.builtin.get_url:
            url: "https://packages.gitlab.com/gpgkey/gpg.key"
            dest: "/etc/apt/keyrings/runner_gitlab-runner-archive-keyrings.gpg"
            mode: "0644"

        - name: Add gitlab runner repository
          ansible.builtin.apt_repository:
            repo: "deb [signed-by=/etc/apt/keyrings/runner_gitlab-runner-archive-keyrings.gpg] https://packages.gitlab.com/runner/gitlab-runner/{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}/ stable main"
            state: present
            filename: runner_gitlab-runner

        - name: install gitlab-runner
          ansible.builtin.apt:
            name: gitlab-runner
            state: latest
            update_cache: true

    - when: ansible_os_family == "RedHat"
      block:
        - name: Import gitlab gpg key
          ansible.builtin.rpm_key:
            key: "https://packages.gitlab.com/runner/gitlab-runner/gpgkey"
            state: present

        - name: add gitlab runner repository
          ansible.builtin.yum_repository:
            name: runner_gitlab-runner
            description: GitLab Runner Repository
            baseurl: "https://packages.gitlab.com/runner/gitlab-runner/el/{{ ansible_distribution_major_version }}/$basearch/"
            gpgkey: "https://packages.gitlab.com/runner/gitlab-runner/gpgkey"
            gpgcheck: true
            repo_gpgcheck: true
            enabled: true

        - name: install gitlab-runner
          ansible.builtin.dnf:
            name: gitlab-runner
            state: latest
            update_cache: true