- name: Setup for ansible
  hosts: "{{ HOSTS_GROUP | default('undefined') }}"
  become: true
  vars:
    password: 
    keys_path: 

  pre_tasks:
    - name: check hosts
      ansible.builtin.assert:
        that:
          - HOSTS_GROUP is defined
        fail_msg: "HOSTS_GROUP variable is not defined."
      run_once: true

  tasks:
    - name: Create Debian user
      ansible.builtin.user:
        name: ansible
        shell: /bin/bash
        append: true
        groups: sudo
        password: "{{ password }}"
        update_password: on_create
      when: ansible_os_family == 'Debian'

    - name: Create RedHat user
      ansible.builtin.user:
        name: ansible
        shell: /bin/bash
        append: true
        groups: wheel
        password: "{{ password }}"
        update_password: on_create
      when: ansible_os_family == 'RedHat'

    - when: ansible_os_family == 'Astra Linux'
      block:
        - name: Create Astra linux user
          ansible.builtin.user:
            name: ansible
            shell: /bin/bash
            append: true
            groups: sudo, astra-console, astra-admin
            password: "{{ password }}"
            update_password: on_create
          
        - name: Check current pdpl policy
          ansible.builtin.command: pdpl-user -p ansible
          register: pdpl_status
          changed_when: false
          failed_when: false

        - name: Apply pdpl
          ansible.builtin.command: pdpl-user -i 63 ansible
          when: "'63' not in pdpl_status.stdout"
          changed_when: true

    - name: create .ssh folder
      ansible.builtin.file:
        path: "/home/ansible/.ssh/"
        state: directory
        owner: ansible
        mode: "0700"

    - name: upload ssh keys
      ansible.builtin.copy:
        src: "{{ keys_path }}"
        dest: "/home/ansible/.ssh/authorized_keys"
        owner: ansible
        mode: "0600"

    - name: Block ssh by password
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        insertafter: EOF
        state: present
        block: |
          Match User ansible
          PasswordAuthentication no

    - name: Restart ssh service for Debian-based
      ansible.builtin.service:
        name: ssh
        state: restarted
      when: ansible_os_family == 'Debian' or ansible_os_family == 'Astra Linux'

    - name: Restart ssh service for RedHat
      ansible.builtin.service:
        name: sshd
        state: restarted
      when: ansible_os_family == 'RedHat'