- name: Setup for ansible
  hosts: "{{ HOSTS_GROUP }}"
  become: true
  vars:
    - password: 
    - keys_path: 

  tasks:
    - name: Create Debian user
      ansible.builtin.user:
        name: ansible
        shell: /bin/bash
        append: true
        groups: sudo
        password: "{{ password }}"
        update_password: on_create
      when: ansible_os_family == 'Debian'

    - name: Create RedHat user
      ansible.builtin.user:
        name: ansible
        shell: /bin/bash
        append: true
        groups: wheel
        password: "{{ password }}"
        update_password: on_create
      when: ansible_os_family == 'RedHat'

    - block:
        - name: Create Astra linux user
          ansible.builtin.user:
            name: ansible
            shell: /bin/bash
            append: true
            groups: sudo, astra-console, astra-admin

        - name: Apply pdpl
          ansible.builtin.shell: pdpl-user -i 63 ansible
      wheel: ansible_os_family == 'Astra Linux'

    - name: create .ssh folder
      ansible.builtin.file:
        path: "/home/ansible/.ssh/"
        state: directory
        owner: ansible

    - name: upload ssh keys
      ansible.builtin.copy:
        src: "{{ keys_path }}"
        dest: "/home/ansible/.ssh/authorized_keys"
        owner: ansible

    - name: Block ssh by password
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        insertafter: EOF
        state: present
        block: |
          Match User ansible
          PasswordAuthentication no

    - name: Restart ssh service for Debian-based
      ansible.builtin.service:
        name: ssh
        state: restarted
      when: ansible_os_family == 'Debian' or ansible_os_family == 'Astra Linux'

    - name: Restart ssh service for RedHat
      ansible.builtin.service:
        name: sshd
        state: restarted
      when: ansible_os_family == 'RedHat'