- name: Createa custom user in linux system
  hosts: "{{ HOSTS_GROUP | default('undefined') }}"
  become: yes
  vars:
    password:

  pre_tasks:
    - name: check hosts
      ansible.builtin.assert:
        that:
          - HOSTS_GROUP is defined
        fail_msg: "HOSTS_GROUP variable is not defined."
      run_once: true

  tasks:
    - name: Create custom user
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/bash
        password: "{{ password }}"
        update_password: on_create
      notify: password expire

  handlers:
    - name: password expire
      ansible.builtin.command: passwd -e "{{ username }}"
      changed_when: true
