- name: Createa custom user in linux system
  hosts: "{{ HOSTS_GROUP }}"
  become: yes

  tasks:
    - name: Create user for Debian
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/bash
        password: "{{ password }}"

    - name: set password expire for first login
      ansible.builtin.shell: passwd -e "{{ username }}"
