- name: Createa custom admin user in linux system
  hosts: "{{ HOSTS_GROUP | default('undefined') }}"
  become: true
  vars:
    password:

  pre_tasks:
    - name: check hosts
      ansible.builtin.assert:
        that:
          - HOSTS_GROUP is defined
        fail_msg: "HOSTS_GROUP variable is not defined."
      run_once: true

  tasks:
    - name: Create user for Debian and RedHat 
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/bash
        append: true
        groups: "{{ 'sudo' if ansible_os_family == 'Debian' else 'wheel' }}"
        password: "{{ password }}"
        update_password: on_create
      notify: password exipre

    - when: ansible_os_family == "Astra Linux"
      block:
      - name: Create user for Astra Linux
        ansible.builtin.user:
          name: "{{ username }}"
          shell: /bin/bash
          append: true
          groups: sudo astra-admin, astra-console
          password: "{{ password }}"
          update_password: on_create
        notify: password exipre

      - name: Check current pdpl policy
        ansible.builtin.command: pdpl-user -p "{{ username }}"
        register: pdpl_status
        changed_when: false
        failed_when: false

      - name: Apply pdpl policy 
        ansible.builtin.command: pdpl-user -i 63 "{{ username }}"
        when: "'63' not in pdpl_status.stdout"
        changed_when: true
  
  handlers:
    - name: password expire
      ansible.builtin.command: passwd -e "{{ username }}"
      changed_when: true
